In [1]:
import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet, LassoCV, lars_path
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline

import statsmodels.api as sm
import statsmodels.formula.api as smf

from collections import defaultdict

In [2]:
lX = np.arange(0, 10)
lY1 = (lX * 2) + 5

In [8]:
lRes = sm.OLS(lY1, lX).fit()
lRes.params

array([2.78947368])

In [10]:
sm.OLS(lY1, lX)

SyntaxError: invalid syntax (<ipython-input-10-f2b8ca446633>, line 1)

In [11]:
lX

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
lY1

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [6]:
lRes2 = sm.OLS(lY1, sm.add_constant(lX)).fit()
lRes2.params

array([5., 2.])

In [12]:
sm.add_constant(lX)

array([[1., 0.],
       [1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.],
       [1., 7.],
       [1., 8.],
       [1., 9.]])

In [19]:
# model = sm.OLS(lY1, sm.add_constant(lX))
model = sm.OLS(lY1, lX, hasconst=False)

In [20]:
model.fit().params

array([2.78947368])